{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-hello-chart.serviceAccountName" . }}
  labels:
{{ include "node-hello-chart.labels" . | nindent 4 }}
{{- end -}}
